name: Draft PDF
on:
  push:
    paths:
    - docs/paper/**
    - .github/workflows/draft-pdf.yml
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Build draft PDF
      uses: openjournals/openjournals-draft-action@master
      with:
        journal: joss
        paper-path: docs/paper/paper.md
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: paper
        path: docs/paper/paper.pdf
